export const products = [
  {
    id: "carpet-01",
    name: "Carpet 01",
    brand: "",
    price: 59.99,
    category: "Carpet",
    description: "A beautiful carpet with a repeating hexagonal geometric pattern in dark blue and light beige tones.",
    fullDescription: "This elegant carpet features a sophisticated hexagonal pattern that adds visual interest to any space. The dark blue base with light beige accents creates a modern, timeless look perfect for contemporary interiors.",
    images: [
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80",
      "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&q=80",
      "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80",
    ],
    styles: ["geometric", "hexagonal", "modern"],
    colors: ["Dark Blue", "Light Beige", "Navy"],
  },
  {
    id: "carpet-02",
    name: "Carpet 02",
    brand: "",
    price: 46.49,
    category: "Carpet",
    description: "The Burgundy Block Pattern Carpet combines rich, deep tones with a striking geometric design, perfect for creating a cozy yet sophisticated atmosphere in any room. The interlocking block pattern adds a modern touch and a sense of depth, making it an eye-catching addition to your home.",
    fullDescription: "The Burgundy Block Pattern Carpet combines rich, deep tones with a striking geometric design, perfect for creating a cozy yet sophisticated atmosphere in any room. The interlocking block pattern adds a modern touch and a sense of depth, making it an eye-catching addition to your home. This versatile piece works beautifully in living rooms, bedrooms, and office spaces.",
    images: [
      "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&q=80",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=80",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80",
      "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80",
    ],
    styles: ["lines", "rectangles", "stripes"],
    colors: ["Burgundy", "Red Clay", "Crimson", "Mahogany"],
  },
  {
    id: "ceramic-tile-01",
    name: "Ceramic Tile 01",
    brand: "",
    price: 42.99,
    category: "Ceramic Tile",
    description: "A light gray tile with a repeating white quatrefoil (four-leaf clover) pattern, adding elegance to any space.",
    fullDescription: "This ceramic tile features a classic quatrefoil pattern that brings timeless elegance to bathrooms, kitchens, and entryways. The light gray base with white pattern creates a sophisticated, clean look.",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
    ],
    styles: ["classic", "ornamental", "traditional"],
    colors: ["Light Gray", "White", "Silver"],
  },
  {
    id: "ceramic-tile-02",
    name: "Ceramic Tile 02",
    brand: "",
    price: 52.99,
    category: "Ceramic Tile",
    description: "A vibrant teal-colored ceramic tile with a glossy finish, arranged in a subway tile pattern.",
    fullDescription: "This vibrant teal ceramic tile features a glossy finish that reflects light beautifully. Perfect for creating a bold statement in modern kitchens and bathrooms.",
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80",
      "https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=800&q=80",
    ],
    styles: ["modern", "subway", "glossy"],
    colors: ["Teal", "Turquoise", "Aqua"],
  },
  {
    id: "ceramic-tile-03",
    name: "Ceramic Tile 03",
    brand: "",
    price: 60.99,
    category: "Ceramic Tile",
    description: "A light beige or off-white ceramic tile with a subtle, mottled texture, showing some reflection.",
    fullDescription: "This elegant ceramic tile features a subtle mottled texture that adds depth and interest. The light beige tone creates a warm, inviting atmosphere.",
    images: [
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    styles: ["textured", "mottled", "natural"],
    colors: ["Beige", "Off-White", "Cream"],
  },
  {
    id: "engineered-flooring",
    name: "Engineered flooring",
    brand: "",
    price: 58.79,
    category: "Flooring",
    description: "Light blonde wood flooring arranged in a herringbone pattern, creating a classic and elegant look.",
    fullDescription: "This engineered flooring features a beautiful herringbone pattern in light blonde wood. The classic pattern adds sophistication while the light color brightens any space.",
    images: [
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80",
    ],
    styles: ["herringbone", "classic", "wood"],
    colors: ["Blonde", "Natural", "Light Oak"],
  },
  {
    id: "hardwood-flooring",
    name: "Hardwood flooring",
    brand: "",
    price: 24.99,
    category: "Flooring",
    description: "Medium brown wood flooring arranged in a complex square parquet pattern.",
    fullDescription: "This hardwood flooring features an intricate square parquet pattern in medium brown. The complex design creates visual interest and timeless elegance.",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80",
    ],
    styles: ["parquet", "geometric", "traditional"],
    colors: ["Medium Brown", "Walnut", "Oak"],
  },
  {
    id: "laminate",
    name: "Laminate",
    brand: "",
    price: 49.99,
    category: "Flooring",
    description: "Light to medium brown laminate flooring with a wood grain pattern, showing individual planks.",
    fullDescription: "This laminate flooring features a realistic wood grain pattern in light to medium brown tones. Durable and easy to maintain, perfect for high-traffic areas.",
    images: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&q=80",
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80",
    ],
    styles: ["wood grain", "plank", "natural"],
    colors: ["Light Brown", "Medium Brown", "Honey"],
  },
  {
    id: "mural",
    name: "Mural",
    brand: "",
    price: 143.99,
    category: "Wall Covering",
    description: "A black and white portrait mural featuring a man wearing glasses and a patterned shirt, holding an old-fashioned telephone receiver.",
    fullDescription: "This striking black and white mural creates a dramatic focal point in any room. The vintage-inspired portrait adds character and artistic flair to your space.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=80",
      "https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=800&q=80",
    ],
    styles: ["vintage", "portrait", "artistic"],
    colors: ["Black", "White", "Monochrome"],
  },
  {
    id: "paint",
    name: "Paint",
    brand: "",
    price: 25.99,
    category: "Wall Covering",
    description: "A solid, soft pink wall paint with a subtle rectangular highlight in the center.",
    fullDescription: "This soft pink paint creates a warm, inviting atmosphere. The subtle highlight adds depth and dimension to your walls.",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-c5f9e2fc7e4e?w=800&q=80",
    ],
    styles: ["solid", "smooth", "modern"],
    colors: ["Soft Pink", "Rose", "Blush"],
  },
  {
    id: "plaster",
    name: "Plaster",
    brand: "",
    price: 29.99,
    category: "Wall Covering",
    description: "A light sage green wall with a repeating wavy or scalloped texture.",
    fullDescription: "This textured plaster finish in light sage green adds visual interest and a natural, organic feel to your walls. The wavy pattern creates movement and depth.",
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-c5f9e2fc7e4e?w=800&q=80",
    ],
    styles: ["textured", "wavy", "organic"],
    colors: ["Sage Green", "Mint", "Seafoam"],
  },
  {
    id: "rug",
    name: "Rug",
    brand: "",
    price: 87.99,
    category: "Carpet",
    description: "A rectangular rug with an abstract design featuring shades of dark blue, light blue, and white, with a distressed or textured appearance.",
    fullDescription: "This abstract rug features a beautiful blend of dark blue, light blue, and white tones. The distressed texture adds character and makes it a perfect statement piece for any room.",
    images: [
      "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=80",
    ],
    styles: ["abstract", "textured", "distressed"],
    colors: ["Dark Blue", "Light Blue", "White"],
  },
];

export const categories = ["All", "Carpet", "Ceramic Tile", "Flooring", "Wall Covering"];

export function getProductById(id) {
  return products.find((product) => product.id === id);
}

export function getProductsByCategory(category) {
  if (category === "All") return products;
  return products.filter((product) => product.category === category);
}

